CREATE TABLE [dbo].[LNK_ROLE_PERMISSION] (
    [Role_Id]       INT NOT NULL,
    [Permission_Id] INT NOT NULL,
    CONSTRAINT [PK_LNK_ROLE_PERMISSION] PRIMARY KEY CLUSTERED ([Role_Id] ASC, [Permission_Id] ASC),
    CONSTRAINT [FK_LNK_ROLE_PERMISSION_PERMISSIONS] FOREIGN KEY ([Permission_Id]) REFERENCES [dbo].[PERMISSIONS] ([Permission_Id]),
    CONSTRAINT [FK_LNK_ROLE_PERMISSION_ROLES] FOREIGN KEY ([Role_Id]) REFERENCES [dbo].[ROLES] ([Role_Id])
);

