CREATE TABLE [dbo].[LNK_USER_ROLE] (
    [User_Id] INT NOT NULL,
    [Role_Id] INT NOT NULL,
    CONSTRAINT [PK_LNK_USER_ROLE] PRIMARY KEY CLUSTERED ([User_Id] ASC, [Role_Id] ASC),
    CONSTRAINT [FK_LNK_USER_ROLE_ROLES] FOREIGN KEY ([Role_Id]) REFERENCES [dbo].[ROLES] ([Role_Id]),
    CONSTRAINT [FK_LNK_USER_ROLE_USERS] FOREIGN KEY ([User_Id]) REFERENCES [dbo].[USERS] ([User_Id])
);

